# Generated by Django 3.0.2 on 2020-05-12 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post_images'),
            preserve_default=False,
        ),
    ]
