# Generated by Django 3.0.2 on 2020-05-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200517_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='image',
            field=models.ImageField(upload_to='media/image'),
        ),
    ]
